#tuple
zoo=("python","elephant","penguin")
print("Number of animals in the zoo is ",len(zoo))
new_zoo="monkey","camel",zoo
print("number of cages in the new zoo is ",len(new_zoo))
print("all animals in new zoo are", new_zoo)
print("new animals brought from old zoo is: ", new_zoo[2])
print("animal brought from old zoo is: ", new_zoo[2][2])
print("the number of animals in the new zoo is ",len(new_zoo)-1+len(new_zoo[2]))
name=("waleed","anus","sufyan")
print(len(name))
print(name)
new_name=("Ahmed","hassan","musab",name)
print(new_name)
print(new_zoo[2][-1])
print(len(new_zoo))